(TeX-add-style-hook "pres_these"
 (lambda ()
    (TeX-run-style-hooks
     "tikz"
     "pgf"
     "amsmath"
     "color"
     "multirow"
     "array"
     "graphicx"
     "verbatim"
     "natbib"
     "fontenc"
     "T1"
     "times"
     "ulem"
     "normalem"
     "soul"
     "exscale"
     "inputenc"
     "utf8"
     "multicol"
     "pst-grad"
     "pstricks"
     "babel"
     "english"
     "latex2e"
     "beamer10"
     "beamer")))

