(TeX-add-style-hook "phD"
 (lambda ()
    (LaTeX-add-bibliographies
     "/home/seb/Documents/biblio_bibtex/biblio_seb")
    (TeX-run-style-hooks
     "tikz"
     "pgf"
     "color"
     "natbib"
     "mathrsfs"
     "amssymb"
     "amsmath"
     "caption"
     "float"
     "graphicx"
     "url"
     "multicol"
     "multirow"
     "array"
     "babel"
     "french"
     "inputenc"
     "utf8"
     "latex2e"
     "rep12"
     "report"
     "12pt"
     "entete2"
     "texte/introduction"
     "texte/article1/article1"
     "texte/article2/upca"
     "texte/article3/camacho"
     "texte/discussion"
     "texte/article1/article1_appendix"
     "texte/article2/appendix_eliza"
     "texte/article3/appendix_diamond/appendix_drift"
     "texte/tdc/tdc")))

